In [1]:
import numpy as np

In [2]:
points2d = np.array([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6]])

In [3]:
points3d = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])

In [4]:
points3d_idxs = np.array([0, 0, 1])

In [5]:
camera_idxs = np.array([0, 1, 2])

In [6]:
P = np.arange(72).reshape((6, 3, 4))

In [7]:
selected_points3d = points3d[points3d_idxs]

In [8]:
print(selected_points3d)

[[1 1 1]
 [1 1 1]
 [2 2 2]]


In [9]:
print(P)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]]

 [[60 61 62 63]
  [64 65 66 67]
  [68 69 70 71]]]


In [10]:
homo_3d_points = np.concatenate((selected_points3d, np.ones((selected_points3d.shape[0], 1))), axis=1)
homo_3d_points_T = np.transpose(homo_3d_points)

In [11]:
homo_3d_points_T

array([[1., 1., 2.],
       [1., 1., 2.],
       [1., 1., 2.],
       [1., 1., 1.]])

In [12]:
calculated_points2d = np.matmul(P, homo_3d_points_T)
print(calculated_points2d)

[[[  6.   6.   9.]
  [ 22.  22.  37.]
  [ 38.  38.  65.]]

 [[ 54.  54.  93.]
  [ 70.  70. 121.]
  [ 86.  86. 149.]]

 [[102. 102. 177.]
  [118. 118. 205.]
  [134. 134. 233.]]

 [[150. 150. 261.]
  [166. 166. 289.]
  [182. 182. 317.]]

 [[198. 198. 345.]
  [214. 214. 373.]
  [230. 230. 401.]]

 [[246. 246. 429.]
  [262. 262. 457.]
  [278. 278. 485.]]]


In [13]:
calculated_points2d = calculated_points2d[camera_idxs, :, points3d_idxs]
print(calculated_points2d)
print(calculated_points2d.shape)
calculated_points2d /= calculated_points2d[:, -1].reshape((calculated_points2d.shape[0], 1))
calculated_points2d = calculated_points2d[:, :-1]

[[  6.  22.  38.]
 [ 54.  70.  86.]
 [102. 118. 134.]]
(3, 3)


In [14]:
print(calculated_points2d)

[[0.15789474 0.57894737]
 [0.62790698 0.81395349]
 [0.76119403 0.88059701]]


In [15]:
i = 2
print("calculated_points2d=", calculated_points2d[i])
print("camera_idxs[0]=", camera_idxs[i])
print("camera =", P[camera_idxs[i]])
print("points3d[0]=", points3d[points3d_idxs[i]])

print("point2d=", points2d[i])

calculated_points2d= [0.76119403 0.88059701]
camera_idxs[0]= 2
camera = [[24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]]
points3d[0]= [2 2 2]
point2d= [3 3]


In [16]:
a = np.arange(1200).reshape((100, 3, 4))

In [17]:
b = np.arange(400).reshape((4, 100))

In [18]:
np.einsum('ijk,ki->ij',a,b)

array([[   1400,    3800,    6200],
       [   8654,   11070,   13486],
       [  16004,   18436,   20868],
       [  23450,   25898,   28346],
       [  30992,   33456,   35920],
       [  38630,   41110,   43590],
       [  46364,   48860,   51356],
       [  54194,   56706,   59218],
       [  62120,   64648,   67176],
       [  70142,   72686,   75230],
       [  78260,   80820,   83380],
       [  86474,   89050,   91626],
       [  94784,   97376,   99968],
       [ 103190,  105798,  108406],
       [ 111692,  114316,  116940],
       [ 120290,  122930,  125570],
       [ 128984,  131640,  134296],
       [ 137774,  140446,  143118],
       [ 146660,  149348,  152036],
       [ 155642,  158346,  161050],
       [ 164720,  167440,  170160],
       [ 173894,  176630,  179366],
       [ 183164,  185916,  188668],
       [ 192530,  195298,  198066],
       [ 201992,  204776,  207560],
       [ 211550,  214350,  217150],
       [ 221204,  224020,  226836],
       [ 230954,  233786,  2

In [19]:
a

array([[[   0,    1,    2,    3],
        [   4,    5,    6,    7],
        [   8,    9,   10,   11]],

       [[  12,   13,   14,   15],
        [  16,   17,   18,   19],
        [  20,   21,   22,   23]],

       [[  24,   25,   26,   27],
        [  28,   29,   30,   31],
        [  32,   33,   34,   35]],

       ...,

       [[1164, 1165, 1166, 1167],
        [1168, 1169, 1170, 1171],
        [1172, 1173, 1174, 1175]],

       [[1176, 1177, 1178, 1179],
        [1180, 1181, 1182, 1183],
        [1184, 1185, 1186, 1187]],

       [[1188, 1189, 1190, 1191],
        [1192, 1193, 1194, 1195],
        [1196, 1197, 1198, 1199]]])

In [20]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
        139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
        152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
        165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 17